name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: >
        sudo apt-get install meson mono-devel dotnet-sdk-8.0
        libnunit-cil-dev nunit-console xsltproc docbook-xsl
    - name: Dotnet gtk-3 deps
      run: >
        dotnet add package GtkSharp --version [3.22,4.0] --package-directory ./libs/gtksharp
        echo "GTKSHARP_LIB=$(realpath libs/gtksharp/gtksharp/*/lib/netstandard2.0)" >> $GITHUB_ENV
    - name: Setup
      run: meson setup build
      env:
        CSCFLAGS: "-r:${{ env.GTKSHARP_LIB }}/glib-sharp.dll -r:${{ env.GTKSHARP_LIB }}/gio-sharp.dll -r:${{ env.GTKSHARP_LIB }}/atk-sharp.dll -r:${{ env.GTKSHARP_LIB }}/gdk-sharp.dll -r:${{ env.GTKSHARP_LIB }}/gtk-sharp.dll"
    - name: Build
      run: ninja -C build
    - name: Run tests
      run: meson test -v -C build
      env:
        MONO_PATH: ${{ env.GTKSHARP_LIB }}
    - name: Install
      run: DESTDIR=/tmp/bless-install ninja -C build install
